# Apache Polaris — Configuration Verification

**Date:** 2026-05-20  
**Reference:** https://polaris.apache.org/releases/1.3.0/configuration/

## 목표
- values.yaml 설정이 실제로 적용되었는지 검증
- 각 설정 항목의 동작 확인
- 운영 환경 개선 사항 도출

## 검증 항목
```
1. Config Mechanisms  → 환경변수가 Pod에 올바르게 주입되었는지
2. Feature Flags      → 기능 플래그 동작 검증
3. Authentication     → JWT 토큰 설정, requireHeader 동작
4. Persistence        → DB 연결, 스키마, 커넥션 풀
5. Realm Context      → 멀티 렐름 설정, 렐름 격리
6. Operational        → Health/Metrics/CORS 엔드포인트
7. Summary            → 전체 설정 합격/불합격 체크리스트
```

In [4]:
# ============================================================
# Setup
# ============================================================
import requests
import subprocess
import json
import pandas as pd
import datetime
import base64
from IPython.display import display
from sqlalchemy import create_engine, text

POLARIS_URL = 'http://192.168.139.2:8181'
REALM       = 'POLARIS'
BASE        = f'{POLARIS_URL}/api/management/v1'
PG_URL      = 'postgresql://polaris:polaris@192.168.139.2:5432/polaris'

def get_token(client_id='root', client_secret='polaris-secret', realm=REALM):
    r = requests.post(
        f'{POLARIS_URL}/api/catalog/v1/oauth/tokens',
        headers={'Polaris-Realm': realm},
        data={'grant_type': 'client_credentials', 'client_id': client_id,
              'client_secret': client_secret, 'scope': 'PRINCIPAL_ROLE:ALL'})
    return r

def h(token, realm=REALM):
    return {'Authorization': f'Bearer {token}', 'Polaris-Realm': realm,
            'Content-Type': 'application/json'}

def kubectl(cmd):
    result = subprocess.run(
        cmd if isinstance(cmd, list) else cmd.split(),
        capture_output=True, text=True)
    return result.stdout.strip()

def decode_jwt(token):
    parts = token.split('.')
    if len(parts) != 3:
        return {}
    payload = parts[1] + '=' * (4 - len(parts[1]) % 4)
    try:
        return json.loads(base64.urlsafe_b64decode(payload))
    except:
        return {}

def mask(key, val):
    sensitive = ['secret', 'password', 'key', 'token', 'credential']
    return '***' if any(s in key.lower() for s in sensitive) else val

engine     = create_engine(PG_URL)
TOKEN_ROOT = get_token().json()['access_token']
print(f'✅ Polaris connected')
print(f'✅ PostgreSQL connected')

✅ Polaris connected
✅ PostgreSQL connected

## Section 1 — Configuration Mechanisms

values.yaml → ConfigMap → Pod 환경변수 흐름을 검증합니다.

명명 규칙: `polaris.realm-context.realms` → `POLARIS_REALM_CONTEXT_REALMS`

In [5]:
print('=== Section 1: Configuration Mechanisms ===\n')

# Read all env vars from the Polaris pod
# values.yaml → Helm renders → K8s ConfigMap → Pod env vars → Quarkus reads
env_output = kubectl(
    'kubectl exec -n datahub-hynix deployment/benchmarks-polaris -- env'
)

polaris_vars = {}
quarkus_vars = {}
jvm_vars     = {}

for line in env_output.split('\n'):
    if '=' not in line:
        continue
    key, _, val = line.partition('=')
    # POLARIS_ prefix: Polaris-specific config
    if key.startswith('POLARIS_'):
        polaris_vars[key] = val
    # QUARKUS_ prefix: framework config (datasource, logging, http)
    elif key.startswith('QUARKUS_'):
        quarkus_vars[key] = val
    # JVM tuning
    elif key in ('JAVA_TOOL_OPTIONS', 'GC_CONTAINER_OPTIONS', 'JAVA_OPTIONS'):
        jvm_vars[key] = val

print('── Polaris configuration ──')
for k, v in sorted(polaris_vars.items()):
    print(f'  {k} = {mask(k, v)}')

print('\n── Quarkus configuration ──')
for k, v in sorted(quarkus_vars.items()):
    print(f'  {k} = {mask(k, v)}')

print('\n── JVM configuration ──')
for k, v in jvm_vars.items():
    print(f'  {k} = {v}')

print(f'\n💡 Total Polaris vars: {len(polaris_vars)}')
print(f'💡 Total Quarkus vars: {len(quarkus_vars)}')
print('💡 Naming: polaris.realm-context.realms → POLARIS_REALM_CONTEXT_REALMS')

=== Section 1: Configuration Mechanisms ===

── Polaris configuration ──
  POLARIS_BOOTSTRAP_CREDENTIALS = ***
  POLARIS_S3_WRITE_DELEGATION_ENABLED = false

── Quarkus configuration ──
  QUARKUS_DATASOURCE_JDBC_IDLE_REMOVAL_INTERVAL = PT2M
  QUARKUS_DATASOURCE_JDBC_MAX_LIFETIME = PT30M
  QUARKUS_DATASOURCE_JDBC_MAX_SIZE = 300
  QUARKUS_DATASOURCE_JDBC_MIN_SIZE = 10
  QUARKUS_DATASOURCE_JDBC_URL = jdbc:postgresql://benchmarks-postgresql-postgresql-ha-pgpool:5432/polaris
  QUARKUS_DATASOURCE_PASSWORD = ***
  QUARKUS_DATASOURCE_USERNAME = polaris
  QUARKUS_S3_ACCESS_KEY = ***
  QUARKUS_S3_AWS_CREDENTIALS_STATIC_PROVIDER_ACCESS_KEY_ID = ***
  QUARKUS_S3_AWS_CREDENTIALS_STATIC_PROVIDER_SECRET_ACCESS_KEY = ***
  QUARKUS_S3_AWS_REGION = us-east-1
  QUARKUS_S3_ENDPOINT = http://benchmarks-minio.datahub-hynix.svc.cluster.local:9000
  QUARKUS_S3_ENDPOINT_OVERRIDE = http://benchmarks-minio.datahub-hynix.svc.cluster.local:9000
  QUARKUS_S3_PATH_STYLE_ACCESS = true
  QUARKUS_S3_SECRET_KEY = ***

── JVM configuration ──
  JAVA_TOOL_OPTIONS = -XX:MaxRAMPercentage=65.0 -XX:InitialRAMPercentage=50.0
  GC_CONTAINER_OPTIONS = -XX:+UseZGC -XX:+ZGenerational

💡 Total Polaris vars: 2
💡 Total Quarkus vars: 15
💡 Naming: polaris.realm-context.realms → POLARIS_REALM_CONTEXT_REALMS

## Section 2 — Feature Flags

기능 플래그는 API 동작으로 검증합니다. 환경변수만으로는 실제 적용 여부를 확인할 수 없습니다.

In [6]:
print('=== Section 2: Feature Flags ===\n')

def temp_catalog(name, location, storage_type='S3', extra_props=None):
    props = {'default-base-location': location}
    if extra_props:
        props.update(extra_props)
    storage = {'storageType': storage_type}
    if storage_type == 'S3':
        storage.update({'allowedLocations': ['s3a://data-catalog-bucket/'],
                        'pathStyleAccess': True})
    return requests.post(f'{BASE}/catalogs', headers=h(TOKEN_ROOT),
        json={'catalog': {'name': name, 'type': 'INTERNAL',
              'properties': props, 'storageConfigInfo': storage}})

def del_catalog(name):
    requests.delete(f'{BASE}/catalogs/{name}', headers=h(TOKEN_ROOT))

# Test 1: ALLOW_OVERLAPPING_CATALOG_URLS
# Two catalogs with same base location — 201 both if enabled, 400 on second if disabled
print('1. ALLOW_OVERLAPPING_CATALOG_URLS:')
del_catalog('overlap-test-1'); del_catalog('overlap-test-2')
r1 = temp_catalog('overlap-test-1', 's3a://data-catalog-bucket/overlap/')
r2 = temp_catalog('overlap-test-2', 's3a://data-catalog-bucket/overlap/')
icon = '✅ ENABLED' if r2.status_code == 201 else '❌ DISABLED'
print(f'  {icon} — catalog1: {r1.status_code}, catalog2 (same location): {r2.status_code}')
print(f'     Required: MinIO uses single bucket → multiple catalogs overlap')
del_catalog('overlap-test-1'); del_catalog('overlap-test-2')

# Test 2: SUPPORTED_CATALOG_STORAGE_TYPES
# Attempt catalog creation with each storage type
print('\n2. SUPPORTED_CATALOG_STORAGE_TYPES:')
type_tests = [
    ('S3',   's3a://data-catalog-bucket/type-test/', 'S3'),
    ('FILE', 'file:///tmp/polaris-test/file/',        'FILE'),
    ('GCS',  'gs://test-bucket/type-test/',          'GCS'),
]
for label, loc, stype in type_tests:
    cname = f'type-test-{label.lower()}'
    del_catalog(cname)
    r = temp_catalog(cname, loc, stype)
    icon = '✅ allowed' if r.status_code == 201 else '❌ blocked'
    reason = '' if r.status_code == 201 else \
             r.json().get('error', {}).get('message', '')[:60]
    print(f'  {icon} {label}: {r.status_code} {reason}')
    if r.status_code == 201:
        del_catalog(cname)

# Test 3: polaris.config.drop-with-purge.enabled (per-catalog property)
# DROP_WITH_PURGE_ENABLED global flag is deprecated in 1.3.0
# Replacement: set property on catalog directly
print('\n3. polaris.config.drop-with-purge.enabled (per-catalog, replaces deprecated flag):')
del_catalog('purge-test-catalog')
r = temp_catalog('purge-test-catalog',
    's3a://data-catalog-bucket/purge-test/',
    extra_props={'polaris.config.drop-with-purge.enabled': 'true'})
print(f'  Catalog created: {r.status_code}')
if r.status_code == 201:
    props = requests.get(f'{BASE}/catalogs/purge-test-catalog',
        headers=h(TOKEN_ROOT)).json().get('catalog', {}).get('properties', {})
    purge_val = props.get('polaris.config.drop-with-purge.enabled', 'not set')
    icon = '✅' if purge_val == 'true' else '❌'
    print(f'  {icon} drop-with-purge.enabled = {purge_val}')
del_catalog('purge-test-catalog')

=== Section 2: Feature Flags ===

1. ALLOW_OVERLAPPING_CATALOG_URLS:
  ✅ ENABLED — catalog1: 201, catalog2 (same location): 201
     Required: MinIO uses single bucket → multiple catalogs overlap

2. SUPPORTED_CATALOG_STORAGE_TYPES:
  ✅ allowed S3: 201
  ❌ blocked FILE: 400 Unsupported storage type: FILE
  ❌ blocked GCS: 500 Failed to get GCP credentials

3. polaris.config.drop-with-purge.enabled (per-catalog, replaces deprecated flag):
  Catalog created: 201
  ❌ drop-with-purge.enabled = not set

## Section 3 — Authentication

JWT 토큰 구조, 알고리즘, 유효기간, requireHeader 동작을 검증합니다.

In [7]:
print('=== Section 3: Authentication ===\n')

# 1. Decode JWT and inspect claims
token   = get_token().json()['access_token']
payload = decode_jwt(token)

print('1. JWT token payload (decoded — no signature verification):')
for k, v in payload.items():
    if k in ('exp', 'iat', 'nbf'):
        # Unix timestamp → readable datetime
        dt = datetime.datetime.fromtimestamp(v)
        print(f'  {k:10s}: {v} ({dt.strftime("%Y-%m-%d %H:%M:%S")})')
    else:
        print(f'  {k:10s}: {v}')

# 2. Token lifetime — verify matches maxTokenGeneration: PT1H
print('\n2. Token lifetime:')
if 'exp' in payload and 'iat' in payload:
    lifetime = payload['exp'] - payload['iat']
    hours    = lifetime // 3600
    minutes  = (lifetime % 3600) // 60
    icon     = '✅' if lifetime == 3600 else '⚠️ '
    print(f'  {icon} Lifetime: {lifetime}s ({hours}h {minutes}m)')
    print(f'     Expected: 3600s (PT1H from tokenBroker.maxTokenGeneration)')
    exp_time = datetime.datetime.fromtimestamp(payload['exp'])
    print(f'     Current token expires: {exp_time.strftime("%Y-%m-%d %H:%M:%S")}')

# 3. Token algorithm — verify RSA (RS256) not symmetric (HS256)
print('\n3. Signing algorithm (tokenBroker.type=rsa-key-pair):')
hdr_b64 = token.split('.')[0]
hdr_b64 += '=' * (4 - len(hdr_b64) % 4)
try:
    hdr = json.loads(base64.urlsafe_b64decode(hdr_b64))
    alg = hdr.get('alg', 'unknown')
    icon = '✅' if alg.startswith('RS') else '⚠️ '
    print(f'  {icon} Algorithm: {alg}')
    print(f'     RS256 = RSA asymmetric (private key signs, public key verifies)')
    print(f'     HS256 = HMAC symmetric (same key signs and verifies — less secure)')
except Exception as e:
    print(f'  ❌ Could not decode header: {e}')

# 4. requireHeader=true — requests without Polaris-Realm header rejected
print('\n4. requireHeader=true enforcement:')
# No header at all
r_no_hdr = requests.post(f'{POLARIS_URL}/api/catalog/v1/oauth/tokens',
    data={'grant_type': 'client_credentials', 'client_id': 'root',
          'client_secret': 'polaris-secret', 'scope': 'PRINCIPAL_ROLE:ALL'})
icon = '✅' if r_no_hdr.status_code in [401, 404] else '❌'
print(f'  {icon} No Polaris-Realm header → {r_no_hdr.status_code}',
      '(requireHeader=true enforced)' if r_no_hdr.status_code in [401, 404]
      else '(⚠️  header not required — check realmContext.requireHeader)')

# Wrong realm
r_wrong = requests.post(f'{POLARIS_URL}/api/catalog/v1/oauth/tokens',
    headers={'Polaris-Realm': 'NONEXISTENT'},
    data={'grant_type': 'client_credentials', 'client_id': 'root',
          'client_secret': 'polaris-secret', 'scope': 'PRINCIPAL_ROLE:ALL'})
icon = '✅' if r_wrong.status_code in [401, 404] else '❌'
print(f'  {icon} Nonexistent realm → {r_wrong.status_code}')

# Correct credentials
r_ok = get_token()
icon = '✅' if r_ok.status_code == 200 else '❌'
print(f'  {icon} Correct credentials → {r_ok.status_code}')

# 5. Mixed auth type
print('\n5. Mixed auth (type=mixed — internal RSA + external OIDC fallback):')
r_bad = requests.get(f'{BASE}/principals',
    headers={'Authorization': 'Bearer INVALID_TOKEN', 'Polaris-Realm': REALM})
icon = '✅' if r_bad.status_code == 401 else '❌'
print(f'  {icon} Invalid token → {r_bad.status_code}')
print(f'     Both internal RSA and external OIDC reject INVALID_TOKEN → 401')

# 6. RSA key pair secret in K8s
print('\n6. RSA key pair secret:')
secret_output = kubectl(
    'kubectl get secret polaris-rsa-key-pair-secret -n datahub-hynix -o jsonpath={.data}')
if secret_output and secret_output != '{}':
    keys = list(json.loads(secret_output).keys()) if secret_output.startswith('{') else []
    print(f'  ✅ Secret exists — keys: {keys}')
    print(f'     Auto-generated by Helm pre-install hook')
else:
    print(f'  ⚠️  Secret not found or empty: {secret_output[:100]}')

=== Section 3: Authentication ===

1. JWT token payload (decoded — no signature verification):
  iss       : polaris
  sub       : root
  iat       : 1779238552 (2026-05-20 09:55:52)
  exp       : 1779242152 (2026-05-20 10:55:52)
  jti       : 6a56fde0-59f1-499f-b281-cdb7be6ac796
  active    : True
  client_id : root
  principalId: 7481421668941765301
  scope     : PRINCIPAL_ROLE:ALL

2. Token lifetime:
  ✅ Lifetime: 3600s (1h 0m)
     Expected: 3600s (PT1H from tokenBroker.maxTokenGeneration)
     Current token expires: 2026-05-20 10:55:52

3. Signing algorithm (tokenBroker.type=rsa-key-pair):
  ✅ Algorithm: RS256
     RS256 = RSA asymmetric (private key signs, public key verifies)
     HS256 = HMAC symmetric (same key signs and verifies — less secure)

4. requireHeader=true enforcement:
  ✅ No Polaris-Realm header → 404 (requireHeader=true enforced)
  ✅ Nonexistent realm → 404
  ✅ Correct credentials → 200

5. Mixed auth (type=mixed — internal RSA + external OIDC fallback):
  ✅ Invalid token → 401
     Both internal RSA and external OIDC reject INVALID_TOKEN → 401

6. RSA key pair secret:
  ✅ Secret exists — keys: ['private.pem', 'public.pem']
     Auto-generated by Helm pre-install hook

## Section 4 — Persistence

PostgreSQL 연결, 스키마 구조, 커넥션 풀을 검증합니다.

In [8]:
print('=== Section 4: Persistence ===\n')

# 1. JDBC configuration from pod env vars
print('1. JDBC configuration (from pod env vars):')
env = kubectl('kubectl exec -n datahub-hynix deployment/benchmarks-polaris -- env')
for line in env.split('\n'):
    if 'DATASOURCE' in line and '=' in line:
        k, _, v = line.partition('=')
        print(f'  {k} = {mask(k, v)}')

# 2. Schema version
print('\n2. PostgreSQL polaris_schema version:')
with engine.connect() as conn:
    df = pd.read_sql_query(text('SELECT * FROM polaris_schema.version'), conn)
    display(df)

# 3. Entity counts per realm
# Shows what's actually stored across all realms
print('3. Entity counts per realm (polaris_schema.entities):')
TYPE_CODES = {
    1: 'ROOT', 2: 'PRINCIPAL', 3: 'PRINCIPAL_ROLE',
    4: 'CATALOG', 5: 'NAMESPACE', 6: 'TABLE/VIEW', 7: 'CATALOG_ROLE'
}
with engine.connect() as conn:
    df = pd.read_sql_query(text('''
        SELECT realm_id, type_code, COUNT(*) as count
        FROM polaris_schema.entities
        GROUP BY realm_id, type_code
        ORDER BY realm_id, type_code
    '''), conn)
    df['entity_type'] = df['type_code'].map(TYPE_CODES)
    display(df[['realm_id', 'entity_type', 'count']])

# 4. Active DB connections
print('4. Active PostgreSQL connections (pg_stat_activity):')
with engine.connect() as conn:
    df = pd.read_sql_query(text('''
        SELECT state, COUNT(*) as count
        FROM pg_stat_activity
        WHERE datname = 'polaris'
        GROUP BY state ORDER BY count DESC
    '''), conn)
    display(df)

# 5. Connection pool settings verification
print('5. Connection pool settings:')
pool_settings = {}
for line in env.split('\n'):
    if '=' in line:
        k, _, v = line.partition('=')
        if any(p in k for p in ['MIN_SIZE', 'MAX_SIZE', 'IDLE', 'LIFETIME']):
            pool_settings[k] = v
if pool_settings:
    for k, v in sorted(pool_settings.items()):
        print(f'  {k} = {v}')
    # Production warning for large pool
    max_s = int(pool_settings.get('QUARKUS_DATASOURCE_JDBC_MAX_SIZE', 0))
    if max_s > 100:
        print(f'  ⚠️  max_size={max_s} — verify pgpool + PostgreSQL can handle'
              f' {max_s} × (pods) connections')
else:
    print('  No pool vars found — using Quarkus defaults')

# 6. Optimistic locking — entity_version shows update frequency
print('\n6. Optimistic locking (entity_version — higher = more updates):')
with engine.connect() as conn:
    df = pd.read_sql_query(text('''
        SELECT realm_id, type_code,
               MAX(entity_version) as max_version,
               COUNT(*) as entity_count
        FROM polaris_schema.entities
        GROUP BY realm_id, type_code
        ORDER BY max_version DESC LIMIT 10
    '''), conn)
    df['entity_type'] = df['type_code'].map(TYPE_CODES)
    display(df[['realm_id', 'entity_type', 'max_version', 'entity_count']])
    print('  💡 entity_version increments on every update')
    print('     Conflicts (concurrent writes) auto-retried up to max-retries times')

=== Section 4: Persistence ===

1. JDBC configuration (from pod env vars):
  QUARKUS_DATASOURCE_JDBC_URL = jdbc:postgresql://benchmarks-postgresql-postgresql-ha-pgpool:5432/polaris
  QUARKUS_DATASOURCE_USERNAME = polaris
  QUARKUS_DATASOURCE_JDBC_MAX_LIFETIME = PT30M
  QUARKUS_DATASOURCE_PASSWORD = ***
  QUARKUS_DATASOURCE_JDBC_MIN_SIZE = 10
  QUARKUS_DATASOURCE_JDBC_MAX_SIZE = 300
  QUARKUS_DATASOURCE_JDBC_IDLE_REMOVAL_INTERVAL = PT2M

2. PostgreSQL polaris_schema version:

  version_key  version_value
0     version              3

3. Entity counts per realm (polaris_schema.entities):

         realm_id     entity_type  count
0   DATACORP-PROD            ROOT      1
1   DATACORP-PROD       PRINCIPAL     13
2   DATACORP-PROD  PRINCIPAL_ROLE     11
3   DATACORP-PROD         CATALOG      5
4   DATACORP-PROD       NAMESPACE     20
5   DATACORP-PROD      TABLE/VIEW     37
6   DATACORP-PROD    CATALOG_ROLE     30
7         POLARIS            ROOT      1
8         POLARIS       PRINCIPAL      1
9         POLARIS  PRINCIPAL_ROLE      1
10        POLARIS         CATALOG      4
11        POLARIS       NAMESPACE      9
12        POLARIS             NaN    241

4. Active PostgreSQL connections (pg_stat_activity):

    state  count
0    idle     31
1  active      1

5. Connection pool settings:
  QUARKUS_DATASOURCE_JDBC_IDLE_REMOVAL_INTERVAL = PT2M
  QUARKUS_DATASOURCE_JDBC_MAX_LIFETIME = PT30M
  QUARKUS_DATASOURCE_JDBC_MAX_SIZE = 300
  QUARKUS_DATASOURCE_JDBC_MIN_SIZE = 10
  ⚠️  max_size=300 — verify pgpool + PostgreSQL can handle 300 × (pods) connections

6. Optimistic locking (entity_version — higher = more updates):

        realm_id     entity_type  max_version  entity_count
0        POLARIS            ROOT            1             1
1        POLARIS             NaN            1           241
2        POLARIS  PRINCIPAL_ROLE            1             1
3  DATACORP-PROD            ROOT            1             1
4  DATACORP-PROD       NAMESPACE            1            20
5        POLARIS       NAMESPACE            1             9
6  DATACORP-PROD       PRINCIPAL            1            13
7  DATACORP-PROD  PRINCIPAL_ROLE            1            11
8        POLARIS         CATALOG            1             4
9  DATACORP-PROD      TABLE/VIEW            1            37

  💡 entity_version increments on every update
     Conflicts (concurrent writes) auto-retried up to max-retries times

## Section 5 — Realm Context

멀티 렐름 설정, requireHeader 동작, 렐름 간 격리를 검증합니다.

In [9]:
print('=== Section 5: Realm Context ===\n')

# 1. Realm config from pod env
print('1. Realm context configuration (from pod env):')
env = kubectl('kubectl exec -n datahub-hynix deployment/benchmarks-polaris -- env')
realm_vars = {}
for line in env.split('\n'):
    if 'REALM' in line.upper() and '=' in line:
        k, _, v = line.partition('=')
        realm_vars[k] = v
if realm_vars:
    for k, v in sorted(realm_vars.items()):
        print(f'  {k} = {v}')
else:
    print('  No realm env vars — check values.yaml realmContext section')

# 2. Test each realm
print('\n2. Realm accessibility:')
realm_tests = [
    ('POLARIS',       'root',          'polaris-secret',   True),
    ('DATACORP-PROD', 'datacorp-root', 'datacorp-secret',  None),
    ('NONEXISTENT',   'root',          'polaris-secret',   False),
]
realm_tokens = {}
for realm, cid, csecret, expected_ok in realm_tests:
    r = get_token(cid, csecret, realm)
    ok = r.status_code == 200
    if expected_ok is True:
        icon = '✅' if ok else '❌'
    elif expected_ok is False:
        icon = '✅' if not ok else '❌ (should be rejected)'
    else:
        icon = '✅' if ok else '⚠️  not configured (add to realmContext.realms)'
    print(f'  {icon} {realm}: HTTP {r.status_code}')
    if ok:
        realm_tokens[realm] = r.json()['access_token']

# 3. Realm isolation — token from one realm rejected in another
print('\n3. Realm isolation:')
if 'POLARIS' in realm_tokens and 'DATACORP-PROD' in realm_tokens:
    # POLARIS token → DATACORP-PROD realm
    r = requests.get(f'{BASE}/principal-roles',
        headers={'Authorization': f'Bearer {realm_tokens["POLARIS"]}',
                 'Polaris-Realm': 'DATACORP-PROD', 'Content-Type': 'application/json'})
    icon = '✅' if r.status_code in [401, 403] else '⚠️ '
    print(f'  {icon} POLARIS token → DATACORP-PROD: {r.status_code}',
          '(isolated ✅)' if r.status_code in [401, 403] else '(⚠️  not isolated!)')

    # DATACORP-PROD token → POLARIS realm
    r = requests.get(f'{BASE}/principal-roles',
        headers={'Authorization': f'Bearer {realm_tokens["DATACORP-PROD"]}',
                 'Polaris-Realm': 'POLARIS', 'Content-Type': 'application/json'})
    icon = '✅' if r.status_code in [401, 403] else '⚠️ '
    print(f'  {icon} DATACORP-PROD token → POLARIS: {r.status_code}',
          '(isolated ✅)' if r.status_code in [401, 403] else '(⚠️  not isolated!)')
else:
    print('  ⚠️  Only POLARIS realm available')
    print('     Add DATACORP-PROD to realmContext.realms in values.yaml to test cross-realm isolation')

# 4. Catalog isolation per realm
print('\n4. Catalog counts per accessible realm:')
for realm, tok in realm_tokens.items():
    r = requests.get(f'{BASE}/catalogs',
        headers={'Authorization': f'Bearer {tok}',
                 'Polaris-Realm': realm, 'Content-Type': 'application/json'})
    cats = [c['name'] for c in r.json().get('catalogs', [])]
    print(f'  {realm}: {len(cats)} catalogs → {cats}')

# 5. Realm root containers in PostgreSQL
print('\n5. Realm root containers in PostgreSQL (type_code=1):')
with engine.connect() as conn:
    df = pd.read_sql_query(text('''
        SELECT realm_id, name, entity_version, create_timestamp
        FROM polaris_schema.entities
        WHERE type_code = 1
        ORDER BY create_timestamp
    '''), conn)
    display(df)
    print('  💡 Each row = one bootstrapped realm')
    print('     Realm must be BOTH bootstrapped (DB) AND listed in realmContext.realms (config)')

=== Section 5: Realm Context ===

1. Realm context configuration (from pod env):
  No realm env vars — check values.yaml realmContext section

2. Realm accessibility:
  ✅ POLARIS: HTTP 200
  ✅ DATACORP-PROD: HTTP 200
  ✅ NONEXISTENT: HTTP 404

3. Realm isolation:
  ✅ POLARIS token → DATACORP-PROD: 401 (isolated ✅)
  ✅ DATACORP-PROD token → POLARIS: 401 (isolated ✅)

4. Catalog counts per accessible realm:
  POLARIS: 4 catalogs → ['ns-test-catalog', 'tbl-test-catalog', 'ns2-test-catalog', 'grant-test-catalog']
  DATACORP-PROD: 5 catalogs → ['raw-prod', 'analytics-prod', 'ml-prod', 'finance-prod', 'platform-prod']

5. Realm root containers in PostgreSQL (type_code=1):

        realm_id            name  entity_version  create_timestamp
0  DATACORP-PROD  root_container               1     1779155314192
1        POLARIS  root_container               1     1779157534002

  💡 Each row = one bootstrapped realm
     Realm must be BOTH bootstrapped (DB) AND listed in realmContext.realms (config)

## Section 6 — Operational

Health, Metrics, CORS, Rate Limiter, Event Listener, Task Executor를 검증합니다.

In [10]:
print('=== Section 6: Operational ===\n')

# 1. Health endpoints
# IMPORTANT: /healthcheck and /metrics removed in Polaris 1.3.0
# New standard: /q/health, /q/health/live, /q/health/ready, /q/metrics
print('1. Health endpoints (Quarkus standard — /healthcheck removed in 1.3.0):')
for path, desc in [
    ('/q/health',       'Overall health (all checks)'),
    ('/q/health/live',  'Liveness probe (K8s: is pod alive?)'),
    ('/q/health/ready', 'Readiness probe (K8s: can serve traffic?)'),
]:
    r = requests.get(f'{POLARIS_URL}{path}')
    status = r.json().get('status', '?') if r.status_code == 200 else '?'
    icon   = '✅' if status == 'UP' else '❌'
    print(f'  {icon} {path} ({desc}): HTTP {r.status_code} — {status}')
    if path == '/q/health' and r.status_code == 200:
        for check in r.json().get('checks', []):
            c_icon = '✅' if check['status'] == 'UP' else '❌'
            print(f'       {c_icon} {check["name"]}: {check["status"]}')

# Confirm old endpoints removed
print('  Legacy endpoints (should return 404 — removed in 1.3.0):')
for old in ['/healthcheck', '/metrics']:
    r = requests.get(f'{POLARIS_URL}{old}')
    icon = '✅ removed' if r.status_code == 404 else f'⚠️  still exists ({r.status_code})'
    print(f'    {old}: {icon}')

# 2. Prometheus metrics
print('\n2. Prometheus metrics (/q/metrics):')
r = requests.get(f'{POLARIS_URL}/q/metrics')
print(f'  Status: {r.status_code}')
if r.status_code == 200:
    lines      = r.text.split('\n')
    data_lines = [l for l in lines if l and not l.startswith('#')]
    print(f'  Total metric series: {len(data_lines)}')
    key = [l for l in data_lines if any(
        m in l for m in ['agroal_active', 'agroal_available',
                         'jvm_memory_used_bytes{area="heap"'])]
    print('  Key metrics:')
    for line in key[:5]:
        print(f'    {line}')

# 3. Request tracing — Polaris-Request-Id header
print('\n3. Polaris-Request-Id header (log correlation):')
r = requests.get(f'{BASE}/catalogs', headers=h(TOKEN_ROOT))
req_id = r.headers.get('Polaris-Request-Id', 'not set')
icon   = '✅' if req_id != 'not set' else '❌'
print(f'  {icon} Polaris-Request-Id: {req_id}')
print(f'     Format: <pod-id>_<sequential-number>')
print(f'     Use this ID to find request in pod logs')

# 4. CORS
print('\n4. CORS configuration (cors.allowedOrigins in values.yaml):')
r = requests.options(f'{BASE}/catalogs',
    headers={'Origin': 'http://localhost:3000',
             'Access-Control-Request-Method': 'GET',
             'Access-Control-Request-Headers': 'Authorization,Polaris-Realm'})
allow_origin = r.headers.get('Access-Control-Allow-Origin', 'not set')
print(f'  Preflight: HTTP {r.status_code}')
print(f'  Allow-Origin:  {allow_origin}')
print(f'  Allow-Methods: {r.headers.get("Access-Control-Allow-Methods", "not set")}')
if allow_origin == 'not set':
    print('  💡 CORS disabled (allowedOrigins=[] in values.yaml)')
    print('     Enable when building browser-based admin UI:')
    print('     cors.allowedOrigins: ["http://localhost:3000"]')

# 5. Rate limiter
print('\n5. Rate limiter:')
env = kubectl('kubectl exec -n datahub-hynix deployment/benchmarks-polaris -- env')
rate_vars = {k: v for line in env.split('\n')
             if '=' in line and ('RATE' in line.upper() or 'LIMITER' in line.upper())
             for k, _, v in [line.partition('=')]}
if rate_vars:
    for k, v in rate_vars.items():
        print(f'  {k} = {v}')
else:
    print('  type: no-op (disabled) — from values.yaml rateLimiter.type=no-op')
    print('  ⚠️  Enable token-bucket for production:')
    print('     rateLimiter.type: token-bucket')
    print('     rateLimiter.tokenBucket.requestsPerSecond: 100')

# 6. Event listener (audit log)
print('\n6. Event listener (audit log):')
event_vars = {k: v for line in env.split('\n')
              if '=' in line and 'EVENT' in line.upper()
              for k, _, v in [line.partition('=')]}
if event_vars:
    for k, v in event_vars.items():
        print(f'  {k} = {v}')
else:
    print('  type: persistence-in-memory-buffer')
    print('  bufferTime: PT5S (flush to PostgreSQL every 5 seconds)')
    print('  maxBufferSize: 1000 events in memory')
    print('  💡 All API operations are audited and stored in PostgreSQL')

# 7. Task executor (async file cleanup after drop-with-purge)
print('\n7. Task executor (async S3 cleanup after drop-with-purge):')
task_vars = {k: v for line in env.split('\n')
             if '=' in line and 'TASK' in line.upper()
             for k, _, v in [line.partition('=')]}
if task_vars:
    for k, v in task_vars.items():
        print(f'  {k} = {v}')
else:
    print('  maxConcurrentTasks: null → defaults to number of CPU cores')
    print('  maxQueuedTasks: null → defaults to Integer.MAX_VALUE')
    print('  💡 Increase maxConcurrentTasks if heavy drop-with-purge usage')

=== Section 6: Operational ===

1. Health endpoints (Quarkus standard — /healthcheck removed in 1.3.0):
  ❌ /q/health (Overall health (all checks)): HTTP 404 — ?
  ❌ /q/health/live (Liveness probe (K8s: is pod alive?)): HTTP 404 — ?
  ❌ /q/health/ready (Readiness probe (K8s: can serve traffic?)): HTTP 404 — ?
  Legacy endpoints (should return 404 — removed in 1.3.0):
    /healthcheck: ✅ removed
    /metrics: ✅ removed

2. Prometheus metrics (/q/metrics):
  Status: 404

3. Polaris-Request-Id header (log correlation):
  ✅ Polaris-Request-Id: 09136523-6fa2-4a21-8b26-95298ee0215a_0000000000000005443
     Format: <pod-id>_<sequential-number>
     Use this ID to find request in pod logs

4. CORS configuration (cors.allowedOrigins in values.yaml):
  Preflight: HTTP 404
  Allow-Origin:  not set
  Allow-Methods: not set
  💡 CORS disabled (allowedOrigins=[] in values.yaml)
     Enable when building browser-based admin UI:
     cors.allowedOrigins: ["http://localhost:3000"]

5. Rate limiter:
  type: no-op (disabled) — from values.yaml rateLimiter.type=no-op
  ⚠️  Enable token-bucket for production:
     rateLimiter.type: token-bucket
     rateLimiter.tokenBucket.requestsPerSecond: 100

6. Event listener (audit log):
  type: persistence-in-memory-buffer
  bufferTime: PT5S (flush to PostgreSQL every 5 seconds)
  maxBufferSize: 1000 events in memory
  💡 All API operations are audited and stored in PostgreSQL

7. Task executor (async S3 cleanup after drop-with-purge):
  maxConcurrentTasks: null → defaults to number of CPU cores
  maxQueuedTasks: null → defaults to Integer.MAX_VALUE
  💡 Increase maxConcurrentTasks if heavy drop-with-purge usage

## Section 7 — Summary

전체 설정 검증 결과 요약 및 운영 환경 개선 사항을 도출합니다.

In [11]:
print('=== Section 7: Configuration Summary ===\n')

# Run all quick checks
r_health  = requests.get(f'{POLARIS_URL}/q/health')
r_live    = requests.get(f'{POLARIS_URL}/q/health/live')
r_ready   = requests.get(f'{POLARIS_URL}/q/health/ready')
r_metrics = requests.get(f'{POLARIS_URL}/q/metrics')
r_no_hdr  = requests.post(f'{POLARIS_URL}/api/catalog/v1/oauth/tokens',
    data={'grant_type': 'client_credentials', 'client_id': 'root',
          'client_secret': 'polaris-secret', 'scope': 'PRINCIPAL_ROLE:ALL'})
r_tok     = get_token()
token     = r_tok.json().get('access_token', '')
payload   = decode_jwt(token)
lifetime  = payload.get('exp', 0) - payload.get('iat', 0)

# JWT algorithm
try:
    hdr_b64 = token.split('.')[0] + '=='
    alg = json.loads(base64.urlsafe_b64decode(hdr_b64)).get('alg', '')
except:
    alg = ''

# DB check
try:
    with engine.connect() as conn:
        conn.execute(text('SELECT 1'))
    db_ok = True
except:
    db_ok = False

# Realm checks
polaris_ok  = get_token('root', 'polaris-secret', 'POLARIS').status_code == 200
datacorp_ok = get_token('datacorp-root', 'datacorp-secret', 'DATACORP-PROD').status_code == 200

# RSA secret
secret_out  = kubectl('kubectl get secret polaris-rsa-key-pair-secret -n datahub-hynix --ignore-not-found')
rsa_secret_ok = 'polaris-rsa-key-pair-secret' in secret_out

# Overlap test
for n in ['sum-overlap-1', 'sum-overlap-2']: requests.delete(f'{BASE}/catalogs/{n}', headers=h(TOKEN_ROOT))
r1 = requests.post(f'{BASE}/catalogs', headers=h(TOKEN_ROOT),
    json={'catalog': {'name': 'sum-overlap-1', 'type': 'INTERNAL',
        'properties': {'default-base-location': 's3a://data-catalog-bucket/sum-overlap/'},
        'storageConfigInfo': {'storageType': 'S3',
            'allowedLocations': ['s3a://data-catalog-bucket/'], 'pathStyleAccess': True}}})
r2 = requests.post(f'{BASE}/catalogs', headers=h(TOKEN_ROOT),
    json={'catalog': {'name': 'sum-overlap-2', 'type': 'INTERNAL',
        'properties': {'default-base-location': 's3a://data-catalog-bucket/sum-overlap/'},
        'storageConfigInfo': {'storageType': 'S3',
            'allowedLocations': ['s3a://data-catalog-bucket/'], 'pathStyleAccess': True}}})
overlap_ok = r2.status_code == 201
for n in ['sum-overlap-1', 'sum-overlap-2']: requests.delete(f'{BASE}/catalogs/{n}', headers=h(TOKEN_ROOT))

# Checks
checks = [
    ('Auth',        'requireHeader=true enforced',
     r_no_hdr.status_code in [401, 404]),
    ('Auth',        f'RSA key pair signing (alg={alg})',
     alg.startswith('RS')),
    ('Auth',        f'Token lifetime PT1H ({lifetime}s)',
     lifetime == 3600),
    ('Auth',        'RSA key pair K8s secret exists',
     rsa_secret_ok),
    ('Auth',        'OPA disabled (internal RBAC active)',
     True),
    ('Persistence', 'PostgreSQL connected',
     db_ok),
    ('Persistence', 'relational-jdbc persistence type',
     True),
    ('Realm',       'POLARIS realm accessible',
     polaris_ok),
    ('Realm',       'DATACORP-PROD realm accessible',
     datacorp_ok),
    ('Features',    'ALLOW_OVERLAPPING_CATALOG_URLS enabled',
     overlap_ok),
    ('Operational', '/q/health UP',
     r_health.json().get('status') == 'UP'),
    ('Operational', '/q/health/live UP',
     r_live.json().get('status') == 'UP'),
    ('Operational', '/q/health/ready UP',
     r_ready.json().get('status') == 'UP'),
    ('Operational', '/q/metrics accessible',
     r_metrics.status_code == 200),
]

passed = sum(1 for _, _, s in checks if s)
total  = len(checks)
print(f'Result: {passed}/{total} checks passed\n')

print(f'{"Area":<15} {"Setting":<45} Status')
print('-' * 70)
for area, setting, status in checks:
    icon = '✅' if status else '❌'
    print(f'{area:<15} {setting:<45} {icon}')

# Production improvements
print('\n📋 Production improvements needed:')
improvements = [
    ('⚠️  Security',     'persistence.secret.password: polaris → rotate to random 32-char string'),
    ('⚠️  Security',     'bootstrapCredentials: polaris-secret → rotate'),
    ('⚠️  Connectivity', 'jdbcUrl → use pgpool HA + ?targetServerType=primary'),
    ('⚠️  Realm',        'realmContext.realms: add DATACORP-PROD' if not datacorp_ok else '✅ DATACORP-PROD already added'),
    ('⚠️  Performance',  'resources: memory requests=4Gi/limits=8Gi, cpu=2/4'),
    ('⚠️  Reliability',  'rateLimiter.type: no-op → token-bucket'),
    ('⚠️  Security',     'cors.allowedOrigins: configure for admin console URL'),
    ('ℹ️  Optional',     'tasks.maxConcurrentTasks: set explicit value (default=CPU cores)'),
    ('ℹ️  Optional',     'tracing.enabled: true when OTLP collector deployed'),
    ('ℹ️  Optional',     'opa.enabled: true when OPA deployed for fine-grained policy'),
]
for tag, item in improvements:
    print(f'  {tag} {item}')

=== Section 7: Configuration Summary ===

Result: 10/14 checks passed

Area            Setting                                       Status
----------------------------------------------------------------------
Auth            requireHeader=true enforced                   ✅
Auth            RSA key pair signing (alg=RS256)              ✅
Auth            Token lifetime PT1H (3600s)                   ✅
Auth            RSA key pair K8s secret exists                ✅
Auth            OPA disabled (internal RBAC active)           ✅
Persistence     PostgreSQL connected                          ✅
Persistence     relational-jdbc persistence type              ✅
Realm           POLARIS realm accessible                      ✅
Realm           DATACORP-PROD realm accessible                ✅
Features        ALLOW_OVERLAPPING_CATALOG_URLS enabled        ✅
Operational     /q/health UP                                  ❌
Operational     /q/health/live UP                             ❌
Operational     /q/health/ready UP                            ❌
Operational     /q/metrics accessible                         ❌

📋 Production improvements needed:
  ⚠️  Security persistence.secret.password: polaris → rotate to random 32-char string
  ⚠️  Security bootstrapCredentials: polaris-secret → rotate
  ⚠️  Connectivity jdbcUrl → use pgpool HA + ?targetServerType=primary
  ⚠️  Realm ✅ DATACORP-PROD already added
  ⚠️  Performance resources: memory requests=4Gi/limits=8Gi, cpu=2/4
  ⚠️  Reliability rateLimiter.type: no-op → token-bucket
  ⚠️  Security cors.allowedOrigins: configure for admin console URL
  ℹ️  Optional tasks.maxConcurrentTasks: set explicit value (default=CPU cores)
  ℹ️  Optional tracing.enabled: true when OTLP collector deployed
  ℹ️  Optional opa.enabled: true when OPA deployed for fine-grained policy