# Apache Polaris — Entities 검증

**Date:** 2026-05-15  
**Reference:** https://polaris.apache.org/releases/1.3.0/entities/

## 학습 목표
- Polaris가 관리하는 9가지 엔티티 타입 실제 데이터로 확인
- Polaris API 응답과 PostgreSQL 직접 조회 결과 비교
- type_code와 엔티티 매핑 이해

## Polaris Entity Types
| type_code | Entity | 설명 |
|-----------|--------|------|
| 1 | ROOT_CONTAINER | 루트 컨테이너 |
| 2 | Principal | 사용자/서비스 계정 |
| 3 | Principal Role | 권한 그룹 |
| 4 | Catalog | Iceberg 카탈로그 |
| 5 | Namespace | 논리적 데이터 그룹 |
| 6 | Table / View | 테이블 또는 뷰 |
| 7 | Catalog Role | 카탈로그 권한 그룹 |
| 8 | Policy | 정책 |

In [12]:
# ============================================================
# Prerequisites
# ============================================================
# uv add requests pandas sqlalchemy psycopg2-binary
# pip install requests pandas sqlalchemy psycopg2-binary
# ============================================================
import subprocess, sys, os
REQUIRED = ['requests', 'pandas', 'sqlalchemy', 'psycopg2-binary']
def install(pkg):
    r = subprocess.run(['uv', 'add', pkg], capture_output=True, text=True, cwd=os.getcwd())
    if r.returncode == 0: return '✅', 'uv'
    r = subprocess.run([sys.executable, '-m', 'pip', 'install', pkg], capture_output=True, text=True)
    return ('✅', 'pip') if r.returncode == 0 else ('❌', 'failed')
for pkg in REQUIRED:
    s, m = install(pkg)
    print(f'  {s} {pkg} ({m})')
print('\n⚠️  Restart kernel after first install.')

  ✅ requests (uv)
  ✅ pandas (uv)
  ✅ sqlalchemy (uv)
  ✅ psycopg2-binary (uv)

⚠️  Restart kernel after first install.

In [13]:
# ============================================================
# Setup
# ============================================================
import requests
import json
import pandas as pd
from IPython.display import display
from sqlalchemy import create_engine, text

POLARIS_URL = 'http://192.168.139.2:8181'
REALM       = 'POLARIS'
PG_URL      = 'postgresql://polaris:polaris@192.168.139.2:5432/polaris'

engine = create_engine(PG_URL)

def get_token(client_id='root', client_secret='polaris-secret'):
    r = requests.post(
        f'{POLARIS_URL}/api/catalog/v1/oauth/tokens',
        headers={'Polaris-Realm': REALM},
        data={'grant_type': 'client_credentials', 'client_id': client_id,
              'client_secret': client_secret, 'scope': 'PRINCIPAL_ROLE:ALL'}
    )
    return r.json()['access_token']

def h(token):
    return {'Authorization': f'Bearer {token}', 'Polaris-Realm': REALM, 'Content-Type': 'application/json'}

def pg(sql):
    with engine.connect() as conn:
        return pd.read_sql_query(text(sql), conn)

TOKEN = get_token()
print(f'✅ Polaris connected')
print(f'✅ PostgreSQL connected')

✅ Polaris connected
✅ PostgreSQL connected

## 1. Catalog
카탈로그는 Polaris의 최상위 엔티티로 Apache Iceberg 카탈로그에 직접 매핑됩니다.
모든 카탈로그는 S3, Azure, GCS, FILE 중 하나의 스토리지 타입을 가집니다.

In [14]:
# 1. Catalog — API
print('=== Catalog (Polaris API) ===')
r = requests.get(f'{POLARIS_URL}/api/management/v1/catalogs', headers=h(TOKEN))
catalogs = r.json().get('catalogs', [])
for c in catalogs:
    print(f"  name           : {c['name']}")
    print(f"  type           : {c.get('type')}")
    print(f"  storageType    : {c.get('storageConfigInfo', {}).get('storageType')}")
    print(f"  location       : {c.get('properties', {}).get('default-base-location')}")
    print(f"  entityVersion  : {c.get('entityVersion')}")
    print()

# PostgreSQL
print('=== Catalog (PostgreSQL entities table) ===')
df = pg("""
    SELECT name, type_code, entity_version,
           internal_properties->>'default-base-location' AS location,
           create_timestamp, last_update_timestamp
    FROM polaris_schema.entities
    WHERE type_code = 4
    ORDER BY create_timestamp
""")
display(df)

=== Catalog (Polaris API) ===
  name           : test-catalog
  type           : INTERNAL
  storageType    : S3
  location       : s3://data-catalog-bucket/test-catalog
  entityVersion  : 1

  name           : ml-catalog
  type           : INTERNAL
  storageType    : S3
  location       : s3a://data-catalog-bucket/ml
  entityVersion  : 1

  name           : analytics-catalog
  type           : INTERNAL
  storageType    : S3
  location       : s3a://data-catalog-bucket/analytics
  entityVersion  : 1

=== Catalog (PostgreSQL entities table) ===

,name,type_code,entity_version,location,create_timestamp,last_update_timestamp
0,test-catalog,4,1,None,1778733122854,1778733122854
1,analytics-catalog,4,1,None,1778824216723,1778824216723
2,ml-catalog,4,1,None,1778824216762,1778824216762

## 2. Namespace
네임스페이스는 카탈로그 내에 존재하는 논리적 엔티티로 테이블과 뷰를 포함합니다.
다른 시스템에서는 스키마 또는 데이터베이스라고 부릅니다. 중첩 가능 (a.b.c.d.e.f.g).

In [15]:
# 2. Namespace — API
print('=== Namespace (Polaris Catalog API) ===')
for c in catalogs:
    cname = c['name']
    r = requests.get(f'{POLARIS_URL}/api/catalog/v1/{cname}/namespaces', headers=h(TOKEN))
    ns_list = r.json().get('namespaces', [])
    for ns in ns_list:
        ns_name = ns[0] if isinstance(ns, list) else ns
        print(f'  {cname} → {ns_name}')

# PostgreSQL
print('\n=== Namespace (PostgreSQL entities table) ===')
df = pg("""
    SELECT e.name, e.type_code, e.entity_version,
           p.name AS parent_catalog,
           e.properties
    FROM polaris_schema.entities e
    LEFT JOIN polaris_schema.entities p ON e.parent_id = p.id AND e.realm_id = p.realm_id
    WHERE e.type_code = 5
    ORDER BY e.create_timestamp
""")
display(df)

=== Namespace (Polaris Catalog API) ===
  test-catalog → test_namespace
  ml-catalog → models
  ml-catalog → experiments
  ml-catalog → features
  analytics-catalog → raw
  analytics-catalog → processed
  analytics-catalog → reporting

=== Namespace (PostgreSQL entities table) ===

                 name  type_code  entity_version     parent_catalog properties
0       catalog_admin          5               1       test-catalog         {}
1  data-engineer-role          5               1       test-catalog         {}
2       catalog_admin          5               1  analytics-catalog         {}
3       catalog_admin          5               1         ml-catalog         {}
4       engineer-role          5               1  analytics-catalog         {}
5        analyst-role          5               1  analytics-catalog         {}
6          admin-role          5               1  analytics-catalog         {}
7             ml-role          5               1         ml-catalog         {}
8          admin-role          5               1         ml-catalog         {}

## 3. Table & View
Polaris 테이블은 Apache Iceberg, Delta, Hudi 테이블에 매핑됩니다.
뷰는 Apache Iceberg 뷰에 매핑되며 읽기 전용 논리적 쿼리입니다.

In [16]:
# 3. Table & View — API
print('=== Table & View (Polaris Catalog API) ===')
for c in catalogs:
    cname = c['name']
    r = requests.get(f'{POLARIS_URL}/api/catalog/v1/{cname}/namespaces', headers=h(TOKEN))
    ns_list = r.json().get('namespaces', [])
    for ns in ns_list:
        ns_name = ns[0] if isinstance(ns, list) else ns
        # Tables
        rt = requests.get(f'{POLARIS_URL}/api/catalog/v1/{cname}/namespaces/{ns_name}/tables', headers=h(TOKEN))
        for t in rt.json().get('identifiers', []):
            print(f'  [TABLE] {cname}.{ns_name}.{t.get("name", t)}')
        # Views
        rv = requests.get(f'{POLARIS_URL}/api/catalog/v1/{cname}/namespaces/{ns_name}/views', headers=h(TOKEN))
        for v in rv.json().get('identifiers', []):
            print(f'  [VIEW]  {cname}.{ns_name}.{v.get("name", v)}')

# PostgreSQL
print('\n=== Table & View (PostgreSQL entities table) ===')
df = pg("""
    SELECT e.name, e.type_code, e.sub_type_code, e.entity_version,
           p.name AS parent_namespace,
           e.internal_properties->>'metadata-location' AS metadata_location
    FROM polaris_schema.entities e
    LEFT JOIN polaris_schema.entities p ON e.parent_id = p.id AND e.realm_id = p.realm_id
    WHERE e.type_code = 6
    ORDER BY e.create_timestamp
""")
display(df)

=== Table & View (Polaris Catalog API) ===
  [TABLE] test-catalog.test_namespace.test_table
  [TABLE] ml-catalog.experiments.experiment_runs
  [TABLE] ml-catalog.features.user_features
  [TABLE] analytics-catalog.raw.users
  [TABLE] analytics-catalog.raw.events
  [TABLE] analytics-catalog.processed.daily_active_users
  [TABLE] analytics-catalog.reporting.monthly_revenue
  [VIEW]  analytics-catalog.reporting.weekly_active_users

=== Table & View (PostgreSQL entities table) ===

,name,type_code,sub_type_code,entity_version,parent_namespace,metadata_location
0,test_namespace,6,0,1,test-catalog,None
1,raw,6,0,1,analytics-catalog,None
2,processed,6,0,1,analytics-catalog,None
3,reporting,6,0,1,analytics-catalog,None
4,features,6,0,1,ml-catalog,None
5,models,6,0,1,ml-catalog,None
6,experiments,6,0,1,ml-catalog,None

## 4. Principal
Principal은 사용자 또는 서비스를 나타내는 고유한 신원입니다.
각 Principal은 하나 이상의 Principal Role을 가질 수 있습니다.

In [17]:
# 4. Principal — API
print('=== Principal (Polaris Management API) ===')
r = requests.get(f'{POLARIS_URL}/api/management/v1/principals', headers=h(TOKEN))
principals = r.json().get('principals', [])
df_api = pd.DataFrame(principals)[['name', 'clientId', 'entityVersion', 'createTimestamp']]
display(df_api)

# PostgreSQL
print('\n=== Principal (PostgreSQL entities table) ===')
df = pg("""
    SELECT name, type_code, entity_version,
           internal_properties->>'client_id' AS client_id,
           create_timestamp
    FROM polaris_schema.entities
    WHERE type_code = 2
    ORDER BY create_timestamp
""")
display(df)
print('\n💡 API clientId == PostgreSQL internal_properties.client_id')

=== Principal (Polaris Management API) ===

            name          clientId  entityVersion  createTimestamp
0           root              root              1    1778724023496
1  spark-service  61f86631c73fcae9              1    1778731831759
2          carol  1968158f66d8d408              1    1778824216460
3            bob  0977fec0fd9c4811              1    1778824216443
4  trino-service  c536c98e00480af0              1    1778824216521
5    etl-service  3abb0ed2e065e538              1    1778824216538
6          alice  892444e249cec8f9              1    1778824216424

=== Principal (PostgreSQL entities table) ===

,name,type_code,entity_version,client_id,create_timestamp
0,root,2,1,root,1778724023496
1,spark-service,2,1,61f86631c73fcae9,1778731831759
2,alice,2,1,892444e249cec8f9,1778824216424
3,bob,2,1,0977fec0fd9c4811,1778824216443
4,carol,2,1,1968158f66d8d408,1778824216460
5,trino-service,2,1,c536c98e00480af0,1778824216521
6,etl-service,2,1,3abb0ed2e065e538,1778824216538

💡 API clientId == PostgreSQL internal_properties.client_id

## 5. Principal Role
Principal Role은 Principal에게 부여되는 레이블입니다.
한 Principal이 여러 Principal Role을 가질 수 있고, 같은 Principal Role이 여러 Principal에게 부여될 수 있습니다.

In [18]:
# 5. Principal Role — API
print('=== Principal Role (Polaris Management API) ===')
r = requests.get(f'{POLARIS_URL}/api/management/v1/principal-roles', headers=h(TOKEN))
roles = r.json().get('roles', [])
df_pr = pd.DataFrame(roles)[['name', 'entityVersion', 'createTimestamp']]
display(df_pr)

# Principal → Role assignments
print('\n=== Principal → Principal Role assignments ===')
for p in principals:
    pname = p['name']
    r = requests.get(f'{POLARIS_URL}/api/management/v1/principals/{pname}/principal-roles', headers=h(TOKEN))
    assigned = [role['name'] for role in r.json().get('roles', [])]
    print(f'  {pname:20s} → {assigned}')

# PostgreSQL
print('\n=== Principal Role (PostgreSQL entities table) ===')
df = pg("""
    SELECT name, type_code, entity_version, create_timestamp
    FROM polaris_schema.entities
    WHERE type_code = 3
    ORDER BY create_timestamp
""")
display(df)

=== Principal Role (Polaris Management API) ===

            name  entityVersion  createTimestamp
0  service_admin              1    1778724023588
1      ops-admin              1    1778824216355
2   data-analyst              1    1778824216322
3    ml-engineer              1    1778824216339
4  data-engineer              1    1778725724061

=== Principal → Principal Role assignments ===
  root                 → ['service_admin']
  spark-service        → ['data-engineer']
  carol                → ['ml-engineer']
  bob                  → ['data-analyst']
  trino-service        → ['data-analyst']
  etl-service          → ['data-engineer']
  alice                → ['ops-admin', 'data-engineer']

=== Principal Role (PostgreSQL entities table) ===

            name  type_code  entity_version  create_timestamp
0  service_admin          3               1     1778724023588
1  data-engineer          3               1     1778725724061
2   data-analyst          3               1     1778824216322
3    ml-engineer          3               1     1778824216339
4      ops-admin          3               1     1778824216355

## 6. Catalog Role
Catalog Role은 카탈로그에 부여되는 레이블입니다.
각 Catalog Role은 여러 Privilege를 가질 수 있으며, 하나 이상의 Principal Role에 부여될 수 있습니다.

In [19]:
# 6. Catalog Role — API
print('=== Catalog Role (Polaris Management API) ===')
for c in catalogs:
    cname = c['name']
    r = requests.get(f'{POLARIS_URL}/api/management/v1/catalogs/{cname}/catalog-roles', headers=h(TOKEN))
    croles = r.json().get('roles', [])
    print(f'  Catalog: {cname}')
    for cr in croles:
        # Get grants for each role
        rg = requests.get(f'{POLARIS_URL}/api/management/v1/catalogs/{cname}/catalog-roles/{cr["name"]}/grants', headers=h(TOKEN))
        grants = [g['privilege'] for g in rg.json().get('grants', [])]
        print(f'    [{cr["name"]}] → {grants}')

# PostgreSQL
print('\n=== Catalog Role (PostgreSQL entities table) ===')
df = pg("""
    SELECT e.name, e.type_code, e.entity_version,
           p.name AS parent_catalog
    FROM polaris_schema.entities e
    LEFT JOIN polaris_schema.entities p ON e.parent_id = p.id AND e.realm_id = p.realm_id
    WHERE e.type_code = 7
    ORDER BY p.name, e.name
""")
display(df)

=== Catalog Role (Polaris Management API) ===
  Catalog: test-catalog
    [catalog_admin] → ['CATALOG_MANAGE_ACCESS', 'CATALOG_MANAGE_METADATA']
    [data-engineer-role] → ['CATALOG_MANAGE_CONTENT']
  Catalog: ml-catalog
    [catalog_admin] → ['CATALOG_MANAGE_ACCESS', 'CATALOG_MANAGE_METADATA']
    [admin-role] → ['CATALOG_MANAGE_ACCESS', 'CATALOG_MANAGE_CONTENT']
    [ml-role] → ['CATALOG_MANAGE_CONTENT', 'NAMESPACE_FULL_METADATA', 'TABLE_WRITE_DATA']
  Catalog: analytics-catalog
    [analyst-role] → ['TABLE_READ_DATA', 'CATALOG_READ_PROPERTIES', 'NAMESPACE_FULL_METADATA', 'TABLE_READ_DATA', 'VIEW_READ_PROPERTIES']
    [engineer-role] → ['CATALOG_MANAGE_CONTENT']
    [admin-role] → ['CATALOG_MANAGE_ACCESS', 'CATALOG_MANAGE_CONTENT']
    [catalog_admin] → ['CATALOG_MANAGE_ACCESS', 'CATALOG_MANAGE_METADATA']

=== Catalog Role (PostgreSQL entities table) ===

                  name  type_code  entity_version  parent_catalog
0      experiment_runs          7               1     experiments
1        user_features          7               1        features
2   daily_active_users          7               1       processed
3               events          7               1             raw
4                users          7               1             raw
5      monthly_revenue          7               1       reporting
6  weekly_active_users          7               1       reporting
7           test_table          7               2  test_namespace

## 7. Privilege
Privilege는 Catalog Role에 부여되어 Principal이 카탈로그 엔티티에 접근할 수 있게 합니다.
Privilege는 카탈로그, 네임스페이스, 테이블, 뷰 레벨로 스코핑 가능합니다.

In [20]:
# 7. Privilege — grant_records table
print('=== Privilege (PostgreSQL grant_records table) ===')

PRIVILEGE_CODES = {
    1: 'CATALOG_MANAGE_ACCESS', 2: 'CATALOG_MANAGE_CONTENT',
    3: 'CATALOG_MANAGE_METADATA', 4: 'CATALOG_READ_PROPERTIES',
    5: 'CATALOG_WRITE_PROPERTIES', 6: 'NAMESPACE_CREATE',
    7: 'NAMESPACE_LIST', 8: 'NAMESPACE_READ_PROPERTIES',
    9: 'NAMESPACE_WRITE_PROPERTIES', 10: 'NAMESPACE_FULL_METADATA',
    11: 'SERVICE_MANAGE_ACCESS', 12: 'PRINCIPAL_ROLE_USAGE',
    13: 'CATALOG_ROLE_USAGE', 14: 'TABLE_READ_DATA',
    15: 'TABLE_WRITE_DATA', 16: 'TABLE_READ_PROPERTIES',
    17: 'TABLE_WRITE_PROPERTIES', 18: 'TABLE_FULL_METADATA',
    19: 'VIEW_READ_PROPERTIES', 20: 'VIEW_WRITE_PROPERTIES',
    21: 'VIEW_FULL_METADATA', 22: 'VIEW_CREATE', 23: 'TABLE_CREATE',
}

df = pg("""
    SELECT
        g.privilege_code,
        e.name  AS grantee_name,
        e.type_code AS grantee_type,
        s.name  AS securable_name,
        s.type_code AS securable_type
    FROM polaris_schema.grant_records g
    LEFT JOIN polaris_schema.entities e ON g.grantee_id = e.id AND g.realm_id = e.realm_id
    LEFT JOIN polaris_schema.entities s ON g.securable_id = s.id AND g.realm_id = s.realm_id
    ORDER BY g.privilege_code
""")

TYPE_CODES = {1:'ROOT', 2:'PRINCIPAL', 3:'PRINCIPAL_ROLE', 4:'CATALOG', 5:'NAMESPACE', 6:'TABLE', 7:'CATALOG_ROLE'}
df['privilege']      = df['privilege_code'].map(PRIVILEGE_CODES)
df['grantee_type']   = df['grantee_type'].map(TYPE_CODES)
df['securable_type'] = df['securable_type'].map(TYPE_CODES)
display(df[['grantee_name', 'grantee_type', 'privilege', 'securable_name', 'securable_type']])
print('\n💡 읽는 방법: grantee가 securable에 대해 privilege를 가진다')

=== Privilege (PostgreSQL grant_records table) ===

,grantee_name,grantee_type,privilege,securable_name,securable_type
0,service_admin,PRINCIPAL_ROLE,CATALOG_MANAGE_ACCESS,root_container,ROOT
1,catalog_admin,NAMESPACE,CATALOG_MANAGE_CONTENT,ml-catalog,CATALOG
2,catalog_admin,NAMESPACE,CATALOG_MANAGE_CONTENT,analytics-catalog,CATALOG
3,admin-role,NAMESPACE,CATALOG_MANAGE_CONTENT,ml-catalog,CATALOG
4,admin-role,NAMESPACE,CATALOG_MANAGE_CONTENT,analytics-catalog,CATALOG
5,catalog_admin,NAMESPACE,CATALOG_MANAGE_CONTENT,test-catalog,CATALOG
6,ops-admin,PRINCIPAL_ROLE,CATALOG_MANAGE_METADATA,admin-role,NAMESPACE
7,data-engineer,PRINCIPAL_ROLE,CATALOG_MANAGE_METADATA,data-engineer-role,NAMESPACE
8,service_admin,PRINCIPAL_ROLE,CATALOG_MANAGE_METADATA,catalog_admin,NAMESPACE
9,ml-engineer,PRINCIPAL_ROLE,CATALOG_MANAGE_METADATA,ml-role,NAMESPACE
10,ops-admin,PRINCIPAL_ROLE,CATALOG_MANAGE_METADATA,admin-role,NAMESPACE
11,service_admin,PRINCIPAL_ROLE,CATALOG_MANAGE_METADATA,catalog_admin,NAMESPACE
12,data-analyst,PRINCIPAL_ROLE,CATALOG_MANAGE_METADATA,analyst-role,NAMESPACE
13,service_admin,PRINCIPAL_ROLE,CATALOG_MANAGE_METADATA,catalog_admin,NAMESPACE
14,data-engineer,PRINCIPAL_ROLE,CATALOG_MANAGE_METADATA,engineer-role,NAMESPACE
15,root,PRINCIPAL,CATALOG_READ_PROPERTIES,service_admin,PRINCIPAL_ROLE
16,spark-service,PRINCIPAL,CATALOG_READ_PROPERTIES,data-engineer,PRINCIPAL_ROLE
17,alice,PRINCIPAL,CATALOG_READ_PROPERTIES,data-engineer,PRINCIPAL_ROLE
18,bob,PRINCIPAL,CATALOG_READ_PROPERTIES,data-analyst,PRINCIPAL_ROLE
19,carol,PRINCIPAL,CATALOG_READ_PROPERTIES,ml-engineer,PRINCIPAL_ROLE
20,trino-service,PRINCIPAL,CATALOG_READ_PROPERTIES,data-analyst,PRINCIPAL_ROLE
21,etl-service,PRINCIPAL,CATALOG_READ_PROPERTIES,data-engineer,PRINCIPAL_ROLE
22,alice,PRINCIPAL,CATALOG_READ_PROPERTIES,ops-admin,PRINCIPAL_ROLE
23,analyst-role,NAMESPACE,TABLE_READ_PROPERTIES,weekly_active_users,CATALOG_ROLE
24,analyst-role,NAMESPACE,VIEW_WRITE_PROPERTIES,analytics-catalog,CATALOG
25,analyst-role,NAMESPACE,VIEW_WRITE_PROPERTIES,events,CATALOG_ROLE
26,ml-role,NAMESPACE,VIEW_FULL_METADATA,user_features,CATALOG_ROLE
27,ml-role,NAMESPACE,VIEW_CREATE,features,TABLE
28,analyst-role,NAMESPACE,VIEW_CREATE,reporting,TABLE
29,analyst-role,NAMESPACE,NaN,analytics-catalog,CATALOG
30,catalog_admin,NAMESPACE,NaN,test-catalog,CATALOG
31,catalog_admin,NAMESPACE,NaN,ml-catalog,CATALOG
32,catalog_admin,NAMESPACE,NaN,analytics-catalog,CATALOG
33,data-engineer-role,NAMESPACE,NaN,test-catalog,CATALOG
34,engineer-role,NAMESPACE,NaN,analytics-catalog,CATALOG
35,admin-role,NAMESPACE,NaN,analytics-catalog,CATALOG
36,admin-role,NAMESPACE,NaN,ml-catalog,CATALOG
37,ml-role,NAMESPACE,NaN,ml-catalog,CATALOG

💡 읽는 방법: grantee가 securable에 대해 privilege를 가진다

## 8. Full Entity Summary
모든 엔티티를 type_code별로 한눈에 확인합니다.

In [21]:
# Full entity summary from PostgreSQL
print('=== All Entities (PostgreSQL) ===')

TYPE_CODES = {
    1: 'ROOT_CONTAINER', 2: 'PRINCIPAL', 3: 'PRINCIPAL_ROLE',
    4: 'CATALOG', 5: 'NAMESPACE', 6: 'TABLE/VIEW', 7: 'CATALOG_ROLE', 8: 'POLICY'
}

df = pg("""
    SELECT
        realm_id, name, type_code, sub_type_code,
        entity_version,
        create_timestamp,
        last_update_timestamp
    FROM polaris_schema.entities
    ORDER BY type_code, create_timestamp
""")

df['entity_type'] = df['type_code'].map(TYPE_CODES)

print(f'\n총 엔티티 수: {len(df)}')
print('\n타입별 개수:')
display(df.groupby(['type_code', 'entity_type']).size().reset_index(name='count'))

print('\n전체 엔티티 목록:')
display(df[['name', 'entity_type', 'entity_version', 'realm_id']])

=== All Entities (PostgreSQL) ===

총 엔티티 수: 41

타입별 개수:

   type_code     entity_type  count
0          1  ROOT_CONTAINER      1
1          2       PRINCIPAL      7
2          3  PRINCIPAL_ROLE      5
3          4         CATALOG      3
4          5       NAMESPACE      9
5          6      TABLE/VIEW      7
6          7    CATALOG_ROLE      8
7          8          POLICY      1

전체 엔티티 목록:

                                 name     entity_type  entity_version realm_id
0                      root_container  ROOT_CONTAINER               1  POLARIS
1                                root       PRINCIPAL               1  POLARIS
2                       spark-service       PRINCIPAL               1  POLARIS
3                               alice       PRINCIPAL               1  POLARIS
4                                 bob       PRINCIPAL               1  POLARIS
5                               carol       PRINCIPAL               1  POLARIS
6                       trino-service       PRINCIPAL               1  POLARIS
7                         etl-service       PRINCIPAL               1  POLARIS
8                       service_admin  PRINCIPAL_ROLE               1  POLARIS
9                       data-engineer  PRINCIPAL_ROLE               1  POLARIS
10                       data-analyst  PRINCIPAL_ROLE               1  POLARIS
11                        ml-engineer  PRINCIPAL_ROLE               1  POLARIS
12                          ops-admin  PRINCIPAL_ROLE               1  POLARIS
13                       test-catalog         CATALOG               1  POLARIS
14                  analytics-catalog         CATALOG               1  POLARIS
15                         ml-catalog         CATALOG               1  POLARIS
16                      catalog_admin       NAMESPACE               1  POLARIS
17                 data-engineer-role       NAMESPACE               1  POLARIS
18                      catalog_admin       NAMESPACE               1  POLARIS
19                      catalog_admin       NAMESPACE               1  POLARIS
20                      engineer-role       NAMESPACE               1  POLARIS
21                       analyst-role       NAMESPACE               1  POLARIS
22                         admin-role       NAMESPACE               1  POLARIS
23                            ml-role       NAMESPACE               1  POLARIS
24                         admin-role       NAMESPACE               1  POLARIS
25                     test_namespace      TABLE/VIEW               1  POLARIS
26                                raw      TABLE/VIEW               1  POLARIS
27                          processed      TABLE/VIEW               1  POLARIS
28                          reporting      TABLE/VIEW               1  POLARIS
29                           features      TABLE/VIEW               1  POLARIS
30                             models      TABLE/VIEW               1  POLARIS
31                        experiments      TABLE/VIEW               1  POLARIS
32                         test_table    CATALOG_ROLE               2  POLARIS
33                             events    CATALOG_ROLE               1  POLARIS
34                              users    CATALOG_ROLE               1  POLARIS
35                 daily_active_users    CATALOG_ROLE               1  POLARIS
36                    monthly_revenue    CATALOG_ROLE               1  POLARIS
37                      user_features    CATALOG_ROLE               1  POLARIS
38                    experiment_runs    CATALOG_ROLE               1  POLARIS
39                weekly_active_users    CATALOG_ROLE               1  POLARIS
40  entityCleanup_1532346270757427849          POLICY               1  POLARIS

## 관찰 결과 (Observations)

- Polaris API 응답과 PostgreSQL 직접 조회 결과가 완전히 일치함
- 모든 엔티티 타입이 단일 `entities` 테이블에 `type_code`로 구분되어 저장됨
- `internal_properties` JSONB에 `metadata-location`, `client_id` 등 내부 정보 포함
- `grant_records` 테이블이 RBAC의 실제 저장소

## 핵심 학습 포인트 (Key Takeaways)

1. Polaris는 9가지 엔티티 타입을 관리하며 모두 PostgreSQL에 저장
2. 권한 흐름: Privilege → Catalog Role → Principal Role → Principal
3. Catalog API와 Management API는 별도 토큰/권한 필요
4. entity_version이 낙관적 잠금으로 동시성 보장